let data = [
	{
		id : 1,
		photo: './photos/1.jpg',
		brand : 'Alexander McQueen',
		type : 'Кофта',
		color : 'Зеленая',
		season : 'Осень/весна',
		useDate : '02.05.2022',
		liked : false,
	},
	{
		id : 2,
		photo: './photos/2.jpg',
		brand : 'Gerry Weber',
		type : 'Платье',
		color : 'Коричневое',
		season : 'Лето',
		useDate : '06.07.2022',
		liked : false,
	},
	{
		id : 3,
		photo: './photos/3.jpg',
		brand : 'Roberto Cavalli',
		type : 'Платье',
		color : 'Синее',
		season : 'Лето',
		useDate : '20.08.2022',
		liked : false,
	},
	{
		id : 4,
		photo: './photos/4.jpg',
		brand : 'Tommy Hilfiger',
		type : 'Футболка',
		color : 'Белая',
		season : 'Лето',
		useDate : '10.08.2022',
		liked : false,
	},
	{
		id : 5,
		photo: './photos/1.jpg',
		brand : 'Karl Lagerfeld',
		type : 'Рубашка',
		color : 'Фиолетовая',
		season : 'Лето',
		useDate : '24.06.2022',
		liked : false,
	},
	{
		id : 6,
		photo: './photos/6.jpg',
		brand : 'Lacoste',
		type : 'Рубашка',
		color : 'Фиолетовая',
		season : 'Лето',
		useDate : '09.09.2022',
		liked : false,
	},
	{
		id : 7,
		photo: './photos/7.jpg',
		brand : 'Blackford',
		type : 'Джемпер',
		color : 'Красная',
		season : 'Осень/весна',
		useDate : '26.01.2023',
		liked : false,
	},
	{
		id : 8,
		photo: './photos/8.jpg',
		brand : 'ТВОЕ',
		type : 'Футболка',
		color : 'Черная',
		season : 'Лето',
		useDate : '09.09.2022',
		liked : false,
	},
	{
		id : 9,
		photo: './photos/9.jpg',
		brand : 'Ben Sherman',
		type : 'Футболка',
		color : 'Зеленая',
		season : 'Лето',
		useDate : '09.09.2022',
		liked : false,
	},
	{
		id : 10,
		photo: './photos/10.jpg',
		brand : 'Bershka',
		type : 'Дубленка',
		color : 'Коричневая',
		season : 'Зима',
		useDate : '13.01.2023',
		liked : false,
	},
]
